TrailLocker/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
//using COS340.TrailLocker.Data;
using TrailLocker.Models;

using TrailLocker.Models.Repository;
using TrailLocker.Models.Entities;

namespace TrailLocker.Controllers
{
    [Authorize]
    public class EquipmentController : Controller
    {
        Repository<Equipment> equipmentRepository;

        public EquipmentController()
        {
            equipmentRepository = new Repository<Equipment>(new DatabaseUnitOfWork());
        }

        public EquipmentController(Repository<Equipment> repo)
        {
            equipmentRepository = repo;
        }

        //
        // GET: /Equipment/

        public ActionResult Index()
        {
            return View(equipmentRepository.FindAll());
        }

        //
        // GET: /Equipment/default

        public ActionResult Default()
        {
            return View(equipmentRepository.FindBy(x => x.IsDefault == true).AsQueryable());
        }

        //
        // GET: /Equipment/DefaultRemove/5

        public ActionResult DefaultRemove(int EquipmentID = 0)
        {
            Equipment item = equipmentRepository.FindBy(x => x.EquipmentID == EquipmentID).Single();
            item.IsDefault = false;
            equipmentRepository.Commit();
            return RedirectToAction("Default");
        }

        //
        // GET: /Equipment/add

        public ActionResult Add()
        {
            return View();
        }

        //
        // POST: /Home/add

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(GeneralEquipment equipmentModel)
        {
            equipmentRepository.Add(equipmentModel);
            equipmentRepository.Commit();
            return RedirectToAction("Index");
        }

        //
        // GET: /Home/Edit/5

        public ActionResult Edit(int EquipmentID = 0)
        {
            Equipment item = equipmentRepository.FindBy(x => x.EquipmentID == EquipmentID).Single();
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Equipment equipmentModel)
        {
            Equipment item = equipmentRepository.FindBy(x => x.EquipmentID == equipmentModel.EquipmentID).Single();
            item.EquipmentID = equipmentModel.EquipmentID;
            item.Category = equipmentModel.Category;
            item.Name = equipmentModel.Name;
            item.Weight = equipmentModel.Weight;
            item.Location = equipmentModel.Location;
            item.IsDefault = equipmentModel.IsDefault;
            equipmentRepository.Commit();
            return RedirectToAction("Index");
        }

        //
        // GET: /Home/Delete/5

        public ActionResult Delete(int EquipmentID = 0)
        {
            Equipment item = equipmentRepository.FindBy(x => x.EquipmentID == EquipmentID).Single();
            equipmentRepository.Remove(item);
            equipmentRepository.Commit();
            return RedirectToAction("Index");
        }

        // GET: /Equipment/search
        public ActionResult Search(EquipmentSearchModel searchParams)
        {
            IQueryable<EquipmentModel> CompleteLocker = CreateEquipment();

            if (!String.IsNullOrEmpty(searchParams.Name))
            {
                CompleteLocker = CompleteLocker.Where(e => e.Name == searchParams.Name);
            }

            if (searchParams.Category != null)
            {
                CompleteLocker = CompleteLocker.Where(e => e.Category == searchParams.Category);
            }

            if (searchParams.MinWeight != null)
            {
                CompleteLocker = CompleteLocker.Where(e => e.Weight >= (int)searchParams.MinWeight);
            }

            if (searchParams.MaxWeight != null)
            {
                CompleteLocker = CompleteLocker.Where(e => e.Weight <= (int)searchParams.MaxWeight);
            }

            return View(CompleteLocker);
        }

        private IQueryable<EquipmentModel> CreateEquipment()
        {
            List<EquipmentModel> equipment = new List<EquipmentModel>();

            //equipment.Add(new EquipmentModel(){Name = "Sleeping Bag", Weight = 2.0, Category = EquipmentCategory.Other, EquipmentID = 1});
            //equipment.Add(new EquipmentModel(){Name = "Pizza", Weight = 120, Category = EquipmentCategory.Perishable, EquipmentID = 2});
            //equipment.Add(new EquipmentModel(){Name = "Water Bottle", Weight = 10, Category = EquipmentCategory.Expendable, EquipmentID = 3});
            //equipment.Add(new EquipmentModel(){Name = "Backpack", Weight = 50, Category = EquipmentCategory.Backpack, EquipmentID = 4});
            //equipment.Add(new EquipmentModel() { Name = "Chips", Weight = 5, Category = EquipmentCategory.Perishable, EquipmentID = 5 });

            return equipment.AsQueryable();
        }
    }
}

TrailLocker/Controllers/TripController.cs
/*Andrew Smith
 * Byrant Sell*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using TrailLocker.Models.Entities;
using TrailLocker.Models.Repository;

//using TrailLocker.Models;

namespace TrailLocker.Controllers
{
    [Authorize]
    public class TripController : Controller
    {
        Repository<Trip> tripRepository;
        InMemoryUnitOfWork unitOfWork;

        public TripController()
            : this(new Repository<Trip>(new DatabaseUnitOfWork()))
        {
            
        }

        public TripController(Repository<Trip> repo)
        {
            tripRepository = repo;
        }


        // GET: /Trip/Trips
        // Routed to by GET: /Trip/
        public ActionResult Trips()
        {
            return View(tripRepository.FindAll());
        }

        //Gets view for adding trip
        //GET: /Trip/AddTrip
        public ActionResult AddTrip()
        {
            return View();
        }

        // POST: /Trip/AddTrip
        [HttpPost]
        public ActionResult AddTrip(Trip tripModel)
        {
            //Add trip to database
            tripRepository.Add(tripModel);
            tripRepository.Commit();
            return RedirectToAction("Index");
        }

        //GET: /Trip/EditTrip
        [HttpGet]
        public ActionResult EditTrip(Trip trip)
        {
            return View(trip);
        }

        // POST: /Trip/EditTripInDatabase
        [HttpPost]
        public ActionResult EditTripInDatabase(Trip trip)
        {
            Trip oldTrip = tripRepository.FindBy(T => T.TripID == trip.TripID).Single();
            oldTrip.StartDate = trip.StartDate;
            oldTrip.EndDate = trip.EndDate;
            oldTrip.DestinationID = trip.DestinationID;
            tripRepository.Commit();
            
            return RedirectToAction("Index");
        }

        // GET: /Trip/DeleteTrip
        public ActionResult DeleteTrip(Trip trip)
        {
            tripRepository.Remove(trip);
            tripRepository.Commit();
            return RedirectToAction("Index");
        }

    }
}

TrailLocker/Views/Shared/_EquipmentLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Scripts.Render("~/bundles/modernizr")
        <script src="Scripts/jquery-1.10.2.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/Content/TrailLocker.css"/>
        <script src="Scripts/events.js"></script>
        <title>Trail Locker</title>
    </head>
    <body id="Locker">
        <header>
            <div id="header">
			    <img id="Logo_in_nav" src="~/Images/traillocker_logo_300px_white.gif" alt="Logo_Up_left" />
                        @{string ctrName = ViewContext.RouteData.Values["action"].ToString();}
                        <ul>
                            <li @if(ctrName=="Index"){<text> class="active"</text>}>@Html.ActionLink("MyLocker","Index","Equipment")</li>
                            <li>@Html.ActionLink("Plan Trip","Index","Trip")</li>
                            <li class="EndDivider" @if(ctrName=="Search"){<text> class="active"</text>}>@Html.ActionLink("Search", "Search","Equipment")</li>
                        </ul>

			
		    </div>
          
        </header>
<!--
        <div id="body">
            <div id="nav_bar_locker_left">
			    <ul >
			       @RenderSection("leftbar")
			    </ul>
			
		    </div> -->
        <div class="gradient" >
            <div id="box_box">
                <section class="content-wrapper main-content clear-fix">
                    @RenderBody()
                </section>
            </div>
        </div>

        <footer>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

TrailLocker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        @*<title>@ViewBag.Title - My ASP.NET MVC Application</title>*@
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @*@Styles.Render("~/Content/css")*@
        @Scripts.Render("~/bundles/modernizr")
        <script src="Scripts/jquery-1.10.2.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/Content/TrailLocker.css"/>
        <script src="Scripts/events.js"></script>
        <title>Trail Locker</title>
    </head>
    <body id="index">
        <header>
            @*<div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home","Index","Home")</li>
                            <li>@Html.ActionLink("Equipment","Index","Equipment")</li>
                            <li>@Html.ActionLink("Search","Search","Equipment")</li>
                            <li>@Html.ActionLink("Trips", "Index","Trip")</li>
                        </ul>
                    </nav>
                </div>
            </div>*@
        </header>
        <div id="body">
            @*@RenderSection("featured", required: false)*@
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            @*<div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>*@
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

TrailLocker/Views/Shared/_TripLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Scripts.Render("~/bundles/modernizr")
        <script src="Scripts/jquery-1.10.2.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/Content/TrailLocker.css"/>
        <script src="Scripts/events.js"></script>
        <title>Trail Locker</title>
    </head>
    <body id="Locker">
        <header>
            <div id="header">
			    <img id="Logo_in_nav" src="~/Images/traillocker_logo_300px_white.gif" alt="Logo_Up_left" />
                        @{string ctrName = ViewContext.RouteData.Values["action"].ToString();}
                        <ul>
                            <li @if(ctrName=="Index"){<text> class="active"</text>}>@Html.ActionLink("MyLocker","Index","Equipment")</li>
                            <li>@Html.ActionLink("Plan Trip","Index","Trip")</li>
                            <li class="EndDivider" @if(ctrName=="Search"){<text> class="active"</text>}>@Html.ActionLink("Search", "Search","Equipment")</li>
                        </ul>

			
		    </div>
          
        </header>
        <div id="body">
        <div class="gradient" >
            @*<div id="nav_bar_locker_left">
			    <ul >
			       @RenderSection("leftbar")
			    </ul>
			
		    </div>*@

            <div id="box_box">
                <section class="content-wrapper main-content clear-fix">
                    @RenderBody()
                </section>
            </div>
        </div>
        </div>
        <footer>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>